name = "Dartis-Craft - Kakusei 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b04485ef9e747191900ca0fb3a0679b7c1ff0439c19f9bde23fdeef4af46d84"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
