name = "Dartis-Craft - Kakusei 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab06b7f4c23eb0fae6443bf51f3742c8fda79e244c80ddddc6e10fda74c065c1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
