name = "Dartis-Craft - Kakusei 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5676448c327fb81606dc43dae9fd36109172462ea460379777747fac23860f73"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
