name = "Dartis-Craft - Kakusei 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea98dca0573a96e12a04fea286856737d431633547cabbf8185583d8b163700d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
